import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Container, Typography } from "@mui/material";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Container>
          <Typography variant="h3">
            Material Design 101
          </Typography>

          <Link href={"/lessons/typography"}>
            <Typography variant="h6" gutterBottom>
              Typography
            </Typography>
          </Link>

          <Link href={"/lessons/stack"}>
            <Typography variant="h6" gutterBottom>
              Stack
            </Typography>
          </Link>

          <Link href={"/lessons/button"}>
            <Typography variant="h6" gutterBottom>
              Button
            </Typography>
          </Link>

          <Link href={"/lessons/buttongroup"}>
            <Typography variant="h6" gutterBottom>
              ButtonGroup
            </Typography>
          </Link>

          {children}
        </Container>

      </body>
    </html>
  );
}
