import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Button, Container, Stack, Typography } from "@mui/material";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Container>

          <Typography variant="h3">
            Material Design 101
          </Typography>

          <Stack direction="row" flexWrap="wrap">
            {
              [
                "Typography",
                "Button",
                "ButtonGroup",
                "ToggleButton",
                "TextField",
                "Select",
                "RadioGroup",
                "CheckBox",
                "Switch",
                "Rating",
                "AutoComplete",
                "Box",
                "Stack",
                "Grid",
                "Paper",
                "Card",
                "Accordion"
              ]
              .map((page,i)=>(
                
                <Button 
                variant="outlined"
                href={`/lessons/${page.toLowerCase()}`}
                key={`b${i}`}>

                  {page}

                </Button>

              ))
            }
          </Stack>

          <Container sx={{marginBottom:"4rem",marginTop:"4rem"}}>
            {children}
          </Container>

        </Container>

      </body>
    </html>
  );
}
